### ISSUE TITLE
Payment not working

### ISSUE THREAD

**Issue by polashmahmud** [karim-007/laravel-bkash-tokenize#3]
The error shows when a mobile number is given in the pop-up box

<img width="1432" alt="Screenshot 2024-01-11 at 10 07 22 PM" src="https://github.com/karim-007/laravel-bkash-tokenize/assets/8996190/d3454b64-06db-469b-96fa-c54cc6346d24">

<img width="762" alt="Screenshot 2024-01-11 at 10 09 55 PM" src="https://github.com/karim-007/laravel-bkash-tokenize/assets/8996190/e934922d-54b2-4f05-a93d-4e42ae1bbce9">

**Comment by karim-007** [comment]
this is not our end issue. this issue from bkash end please contact with them.
